<a href="https://colab.research.google.com/github/kristynpantoja/math689project/blob/master/pytorchM1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
!pip install torch

In [2]:
!pip install torchvision

Model Parameters

In [252]:
# from types import SimpleNamespace

# args_dict = {"batch_size" : 50, "epochs" : 50, "no_cuda" : False, "seed" : 1, "log_interval" : 10}
# args = SimpleNamespace(**args_dict)
# args.epochs

50

In [393]:
!pip install gensim

    100% |████████████████████████████████| 23.6MB 698kB/s 
    100% |████████████████████████████████| 1.4MB 12.5MB/s 
    100% |████████████████████████████████| 133kB 24.1MB/s 
    100% |████████████████████████████████| 61kB 19.6MB/s 
    100% |████████████████████████████████| 4.7MB 6.0MB/s 
    100% |████████████████████████████████| 552kB 23.8MB/s 
  Running setup.py bdist_wheel for smart-open ... - \ done
  Stored in directory: /root/.cache/pip/wheels/23/00/44/e5b939f7a80c04e32297dbd6d96fa3065af89ecf57e2b5f89f
  Running setup.py bdist_wheel for bz2file ... - done
  Stored in directory: /root/.cache/pip/wheels/81/75/d6/e1317bf09bf1af5a30befc2a007869fa6e1f516b8f7c591cb9
Successfully built smart-open bz2file


Data: 20newsgroups
We get the document-term matrix

In [1]:
from __future__ import print_function
import argparse
import torch
import torch.utils.data
from torch import nn, optim
from torch.nn import functional as F
from torchvision import datasets, transforms
from torchvision.utils import save_image

from types import SimpleNamespace

from sklearn.datasets import fetch_20newsgroups
import numpy as np
import torch
# from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity

from sklearn.feature_extraction.text import CountVectorizer
# categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space']
# newsgroups_train = fetch_20newsgroups(subset='train', categories=categories)
newsgroups_train = fetch_20newsgroups(subset='train')
vectorizer = CountVectorizer(min_df=.01, max_df=0.05, stop_words = 'english',
                             token_pattern = u'(?ui)\\b[a-z]{3,}\\b')
count_vecs = vectorizer.fit_transform(newsgroups_train.data)
doc_term_matrix = count_vecs.toarray()
doc_term_matrix.shape # number of documents, number of words (in vocab)

(11314, 1544)

In [0]:
vectorizer.get_feature_names()

ragged array of words in each document (by index in vocabulary)

In [0]:
def countsToInput(row):
  return np.repeat(np.arange(doc_term_matrix.shape[1]),row)
  
def numWords(row):
  return row.sum()

N_train = np.apply_along_axis(numWords, axis=1, arr=doc_term_matrix)
data_train = []
for d in range(doc_term_matrix.shape[0]):
  data_train.append(torch.from_numpy(countsToInput(doc_term_matrix[d])))



In [20]:
data_train[1030]

tensor([  27,   65,  160,  160,  161,  161,  240,  266,  323,  339,  416,  427,
         549,  617,  658,  772,  844,  844,  844, 1082, 1083, 1099, 1120, 1120,
        1120, 1120, 1120, 1124, 1165, 1214, 1292, 1297, 1318, 1333, 1449])

## Word2vec

## Setup for Model

In [0]:


# from types import SimpleNamespace


# args_dict = {"batch_size" : 50, "epochs" : 50, "no_cuda" : False, "seed" : 1, "log_interval" : 10}
# args = SimpleNamespace(**args_dict)
# args.cuda = not args.no_cuda and torch.cuda.is_available()


args_dict = {"batch_size" : 50, "epochs" : 50, "no_cuda" : False, "seed" : 1, "log_interval" : 100}
args = SimpleNamespace(**args_dict)






####3


args.cuda = not args.no_cuda and torch.cuda.is_available()

torch.manual_seed(args.seed)

device = torch.device("cuda" if args.cuda else "cpu")

kwargs = {'num_workers': 1, 'pin_memory': True} if args.cuda else {}
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.ToTensor()),
    batch_size=args.batch_size, shuffle=True, **kwargs)
test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, transform=transforms.ToTensor()),
    batch_size=args.batch_size, shuffle=True, **kwargs)





Define model

In [0]:
class VAE(nn.Module):
    def __init__(self, num_docs):
        super(VAE, self).__init__()
        
        vocab_size = doc_term_matrix.shape[1]
        wordvec_dim = 100
        encoder_hidden = 256
        rp_normal_dim = 100
        K = 6
        self.num_docs = num_docs
        self.word_embedding = nn.Embedding(vocab_size, wordvec_dim) # decoder
        self.topic_embedding = nn.Embedding(K, wordvec_dim) # decoder
        self.lin1 = nn.Linear(vocab_size, encoder_hidden) # encoder
        self.mean = nn.Linear(encoder_hidden, rp_normal_dim) # encoder
        self.logvar = nn.Linear(encoder_hidden, rp_normal_dim) # encoder
        self.lin2 = nn.Linear(rp_normal_dim, K) # decoder 
        #self.topicslayer = nn.Linear(wordvec_dim, K) # decoder
        self.beta = torch.zeros([K, vocab_size], dtype = torch.float32) # decoder

    def encode(self, x):
#         h1 = F.relu(self.lin1(x))
        h1 = self.lin1(x)
        return self.mean(h1), self.logvar(h1)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5*logvar)
        eps = torch.randn_like(std)
        return eps.mul(std).add_(mu) # this gives x ~ N(mu, var)

      
    def decode(self, z):
        x = self.lin2(z) 
        theta = F.softmax(x, dim = 1) # to get theta, dim = batch size x K
        #word_dot_topic = self.topicslayer(self.word_embedding.weight) # weights corresp to topic vector
        self.beta = F.softmax(torch.mm(self.word_embedding.weight, 
                                       torch.transpose(self.topic_embedding.weight, 0, 1)), dim = 0) # beta dim = V x K
        log_theta_dot_beta = torch.log(torch.mm(theta, torch.transpose(self.beta, 0, 1))) # dim = batch size x V
        #theta_dot_beta = torch.exp(log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0))
        ####log_theta_dot_beta_normalized = log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0)
        return log_theta_dot_beta ####log_theta_dot_beta_normalized
        
    def forward(self, doc):
        mu, logvar = self.encode(doc)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar, self.topic_embedding.weight
        


      


Load training data (separate into batches)

In [0]:
# mnist_train_loader = torch.utils.data.DataLoader(
#     datasets.MNIST('../data', train=True, download=True,
#                    transform=transforms.ToTensor()),
#     batch_size=args.batch_size, shuffle=True, **kwargs)
# # enumerate(train_loader)

train_data = torch.utils.data.TensorDataset(torch.tensor(doc_term_matrix))
train_loader = torch.utils.data.DataLoader(train_data,                                            
    batch_size = args.batch_size, shuffle = True)

instantiate model and define functions for training

In [0]:
model = VAE(doc_term_matrix.shape[1]).to(device) 
      
optimizer = optim.Adam(model.parameters(), lr=1e-3)
# optimizer = optim.RMSprop(model.parameters(), lr = 1e-3)

# Reconstruction + KL divergence losses summed over all elements and batch
def loss_function(log_theta_dot_beta, x, mu, logvar, t):
    BCE = log_theta_dot_beta.sum()
    KLD = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
#     K = t.shape[0]
#     arccos = []
#     for j in range(K):
#         for k in range(j, K):
#             arccos.append(torch.acos(torch.dot(t[:, j], t[:, k]) /
#                                                    (max(t[:, j].norm() * t[:, k].norm(), 1e-5))))
#             arccos.append(F.cosine_similarity(t[:, j], t[:, k]))
#     arccos = torch.tensor(arccos)
#     print(arccos.max())
#     zeta = (1 / (K * K)) * arccos.sum()
#     nu = torch.zeros(1)
#     print("zeta: " + str(zeta) + "nu: " + str(nu))
#     for a in arccos:
#         nu = nu.add((a - zeta).pow(2))
#     nu = (1 / (K * K)) * nu
    return - BCE + KLD# - .1 * (zeta - nu)

enc_variables = list(model.lin1.parameters()) + list(model.mean.parameters()) +  list(model.logvar.parameters())
dec_variables = list(model.word_embedding.parameters()) + list(model.lin2.parameters()) + list(model.topic_embedding.parameters())


optim_enc = optim.Adam(enc_variables, lr=1e-3)
optim_dec = optim.Adam(dec_variables, lr=1e-3)

def train(epoch):
    model.train()
    train_loss = 0
#     for switch in range(0,2):
#         if switch == 0:
#             print("updating encoder variables")
#             optimizer = optim_enc
#         else:
#             print("updating decoder variables")
#             optimizer = optim_dec
    for batch_idx, data in enumerate(train_loader):
        #data = data.to(device)
        optimizer.zero_grad()
        log_theta_beta, mu, logvar, topic_vecs = model(data[0].float())
        loss = loss_function(log_theta_beta, data, mu, logvar, topic_vecs)
        loss.backward()
        train_loss += loss.item()
        optimizer.step()
        if batch_idx % args.log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * data[0].shape[0], len(train_loader.dataset),
                100. * batch_idx / len(train_loader),
                loss.item() / data[0].shape[0]))

    print('====> Epoch: {} Average loss: {:.4f}'.format(
          epoch, train_loss / len(train_loader.dataset)))

    return train_loss / len(train_loader.dataset)


# def test(epoch):
#     model.eval()
#     test_loss = 0
#     with torch.no_grad():
#         for i, (data, _) in enumerate(test_loader):
#             data = data.to(device)
#             recon_batch, mu, logvar = model(data)
#             test_loss += loss_function(recon_batch, data, mu, logvar).item()
#             if i == 0:
#                 n = min(data.size(0), 8)
#                 comparison = torch.cat([data[:n],
#                                       recon_batch.view(args.batch_size, 1, 28, 28)[:n]])
# #                 save_image(comparison.cpu(),
# #                          'results/reconstruction_' + str(epoch) + '.png', nrow=n)

#     test_loss /= len(test_loader.dataset)
#     print('====> Test set loss: {:.4f}'.format(test_loss))

# if __name__ == "__main__":
#     for epoch in range(1, args.epochs + 1):
#         train(epoch)
#         test(epoch)
#         with torch.no_grad():
#             sample = torch.randn(64, 20).to(device)
#             sample = model.decode(sample).cpu()
#             save_image(sample.view(64, 1, 28, 28),
#                        'results/sample_' + str(epoch) + '.png')

 train the model

In [0]:
#model = VAE(doc_term_matrix.shape[1])#.to(device)

In [425]:
losses = []
for epoch in range(1, args.epochs + 1):
    losses.append(train(epoch))
    if epoch > 1:
        if np.abs(losses[epoch-1] - losses[epoch-2]) < 1e-2:
            break


Train Epoch: 1 [0/11314 (0%)]	Loss: 38085.567500
Train Epoch: 1 [5000/11314 (44%)]	Loss: 14909.576250
Train Epoch: 1 [10000/11314 (88%)]	Loss: 11513.456250
====> Epoch: 1 Average loss: 1778555.3972
Train Epoch: 2 [0/11314 (0%)]	Loss: 11422.237500
Train Epoch: 2 [5000/11314 (44%)]	Loss: 11381.053750
Train Epoch: 2 [10000/11314 (88%)]	Loss: 11383.158750
====> Epoch: 2 Average loss: 235546620754.3593
Train Epoch: 3 [0/11314 (0%)]	Loss: 11387.018750
Train Epoch: 3 [5000/11314 (44%)]	Loss: 11441.125000
Train Epoch: 3 [10000/11314 (88%)]	Loss: 11433.386250
====> Epoch: 3 Average loss: 298834.8986
Train Epoch: 4 [0/11314 (0%)]	Loss: 11361.048750
Train Epoch: 4 [5000/11314 (44%)]	Loss: 11386.891250
Train Epoch: 4 [10000/11314 (88%)]	Loss: 11364.223750
====> Epoch: 4 Average loss: 11400.2419
Train Epoch: 5 [0/11314 (0%)]	Loss: 11492.270000
Train Epoch: 5 [5000/11314 (44%)]	Loss: 11363.186250
Train Epoch: 5 [10000/11314 (88%)]	Loss: 11363.101250
====> Epoch: 5 Average loss: 11561.9956
Train Epoc

KeyboardInterrupt: ignored

In [426]:
model.beta
_, ind = torch.sort(model.beta, 0)
# ind.numpy()[0:50, 0] - ind.numpy()[0:50, 1]
print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 0])
print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 1])
print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 2])
print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 3])
print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 4])
print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 5])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 7])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 8])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 9])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 15])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 19])

['special' 'poster' 'wouldn' 'christians' 'service' 'guest' 'library'
 'names' 'forces' 'pat' 'utexas' 'follow' 'copy' 'meant' 'nation'
 'relevant' 'chips' 'sea' 'hours' 'sick']
['wants' 'lab' 'cambridge' 'status' 'flames' 'box' 'noted' 'drug'
 'companies' 'criminal' 'cmu' 'color' 'particular' 'corp' 'suspect'
 'despite' 'graphics' 'options' 'steve' 'copies']
['christians' 'forget' 'open' 'games' 'style' 'respect' 'received'
 'transfer' 'clear' 'max' 'hall' 'disclaimer' 'jews' 'matter' 'added'
 'caught' 'clock' 'change' 'specific' 'scsi']
['sex' 'latest' 'comparison' 'bear' 'player' 'open' 'speed' 'difficult'
 'week' 'fbi' 'issues' 'christ' 'freenet' 'listen' 'apply' 'banks'
 'covered' 'appear' 'update' 'spot']
['advanced' 'nature' 'took' 'sold' 'twice' 'interface' 'broken' 'guy'
 'tony' 'algorithm' 'patrick' 'sign' 'office' 'lord' 'country' 'ide'
 'acts' 'rob' 'track' 'buying']
['food' 'guide' 'ice' 'ran' 'months' 'correct' 'conditions' 'readers'
 'outside' 'copies' 'rocket' 'design' 

In [406]:
# a = torch.randn(100, 128)
a = torch.tensor([[1,2,3], [4,5,6]]).float()
b = torch.tensor([[1,2,3], [4,5,6]]).float()

F.cosine_similarity(a, b)

tensor([1.0000, 1.0000])

Get word vectors and topic vectors

In [341]:
a = torch.tensor([1])
a.add(torch.tensor([2]))
print(a)

tensor([1])


In [255]:
for i in range(0, 2):
  print(i)

0
1


In [187]:
to

Parameter containing:
tensor([[ 1.0982, -0.6489,  0.0177,  ...,  0.7344,  0.6163,  0.6307],
        [-0.6461,  0.5238, -0.1179,  ..., -1.1260, -0.5322,  0.7694],
        [ 1.2182,  0.6254,  0.0470,  ...,  1.6700,  0.4856,  2.6060],
        ...,
        [ 0.5594,  1.2776,  1.0770,  ...,  0.8158,  1.5054, -0.4085],
        [ 1.0393, -0.1039,  0.9977,  ...,  1.5477, -0.1037,  0.0440],
        [ 0.7130,  1.8861, -1.6776,  ..., -0.1981,  1.5925, -1.3581]],
       requires_grad=True)

Get topic distributions

In [183]:
unscaled_topics = torch.mm(model.word_embedding(torch.tensor(np.arange(doc_term_matrix.shape[1]))),
         torch.transpose(model.topicslayer.weight, 0, 1))
topic_dist = torch.softmax(unscaled_topics, dim = 0) 
topic_dist.sum(dim = 0)

tensor([1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)

This one helped us a lot

In [270]:
#model.encode(torch.LongTensor(doc_term_matrix[0]))
#input = torch.tensor(doc_term_matrix).float()
input = torch.tensor(doc_term_matrix).float()[[0, 1], ]
mu, sigma = model.encode(input)
z = model.reparameterize(mu, sigma)
# model.decode(x, input.shape[0])

x = model.fc3(z)
theta = F.softmax(x) # to get theta
embedding_matrix = model.word_embedding(torch.tensor(np.arange(14)))
word_dot_topic = model.fc4(embedding_matrix) # weights corresp to topic vector
beta = F.softmax(word_dot_topic)
log_theta_dot_beta = torch.log(torch.mm(theta, torch.transpose(beta, 0, 1)))
#theta_dot_beta = torch.exp(log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0))
log_theta_dot_beta_normalized = log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0)
# print(theta.shape)
# print(theta)
# print(embedding_matrix)
# print(word_dot_topic)
print(beta.shape)
print(beta)
print(log_theta_dot_beta)
print(torch.exp(log_theta_dot_beta_normalized))


AttributeError: ignored

In [284]:
#model.encode(torch.LongTensor(doc_term_matrix[0]))
#input = torch.tensor(doc_term_matrix).float()
input = torch.tensor(doc_term_matrix).float()[[0, 1], ]
print(input)
mu, sigma = model.encode(input)
z = model.reparameterize(mu, sigma)
print(z)
# model.decode(x, input.shape[0])


# x = model.lin2(z)
# theta = F.softmax(x) # to get theta
# embedding_matrix = model.word_embedding(torch.tensor(np.arange(model.num_docs)))
# word_dot_topic = model.topicslayer(embedding_matrix) # weights corresp to topic vector
# model.beta = F.softmax(word_dot_topic, dim = 0)
# log_theta_dot_beta = torch.log(torch.mm(theta, torch.transpose(model.beta, 0, 1)))
# #theta_dot_beta = torch.exp(log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0))
# log_theta_dot_beta_normalized = log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0)
# print(embedding_matrix.shape) # dim of embedding matrix is 1544 x 100


x = model.lin2(z)
theta = F.softmax(x, 1) # to get theta
print(theta.sum(1))
embedding_matrix = model.word_embedding.weight
print(model.word_embedding(torch.tensor(np.arange(model.num_docs))).shape)
print(embedding_matrix.shape)
word_dot_topic = model.topicslayer(embedding_matrix) # weights corresp to topic vector
model.beta = F.softmax(word_dot_topic, dim = 0)
log_theta_dot_beta = torch.log(torch.mm(theta, torch.transpose(model.beta, 0, 1)))
#theta_dot_beta = torch.exp(log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0))
log_theta_dot_beta_normalized = log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0)
# print(embedding_matrix.shape) # dim of embedding matrix is still 1544 x 100


tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[-0.3542, -0.9824,  1.6668,  0.2909, -1.7727,  1.6447, -0.0335, -0.3574,
         -1.0229,  0.9524,  0.7662, -0.0573,  0.7221, -0.9453,  0.6689, -0.3142,
          1.1116, -0.5060, -0.5279,  0.1749,  0.5559, -0.7530, -0.2019, -0.1538,
          1.5552],
        [ 1.1045,  0.5738, -1.3214,  0.2868,  0.1640, -0.9203,  0.2256, -1.9079,
         -0.8485, -0.1582,  0.7142, -0.5238,  0.4466, -0.1109,  0.0060,  0.5935,
         -2.4257, -1.1120, -0.1708, -0.0022, -3.3380, -0.6230, -0.6414,  2.1400,
          0.5324]], grad_fn=<ThAddBackward>)
tensor([1.0000, 1.0000], grad_fn=<SumBackward1>)
torch.Size([1544, 100])
torch.Size([1544, 100])
