<a href="https://colab.research.google.com/github/kristynpantoja/math689project/blob/master/pytorchM2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch

    100% |████████████████████████████████| 519.5MB 26kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x59e42000 @  0x7fce1832c2a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070


In [2]:
!pip install torchvision

    100% |████████████████████████████████| 61kB 3.6MB/s 
    100% |████████████████████████████████| 2.0MB 7.9MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


Model Parameters

In [3]:
!pip install gensim

    100% |████████████████████████████████| 23.6MB 1.3MB/s 
    100% |████████████████████████████████| 1.4MB 11.7MB/s 
    100% |████████████████████████████████| 133kB 29.0MB/s 
    100% |████████████████████████████████| 61kB 22.2MB/s 
    100% |████████████████████████████████| 4.7MB 6.3MB/s 
    100% |████████████████████████████████| 552kB 21.4MB/s 
  Running setup.py bdist_wheel for smart-open ... - done
  Stored in directory: /root/.cache/pip/wheels/23/00/44/e5b939f7a80c04e32297dbd6d96fa3065af89ecf57e2b5f89f
  Running setup.py bdist_wheel for bz2file ... - done
  Stored in directory: /root/.cache/pip/wheels/81/75/d6/e1317bf09bf1af5a30befc2a007869fa6e1f516b8f7c591cb9
Successfully built smart-open bz2file


In [0]:
from __future__ import print_function
import argparse
import torch
import torch.utils.data
from torch import nn, optim
from torch.nn import functional as F
from torchvision import datasets, transforms
from torchvision.utils import save_image

from types import SimpleNamespace

from sklearn.datasets import fetch_20newsgroups
import numpy as np
import torch

from sklearn.metrics.pairwise import cosine_similarity

from sklearn.feature_extraction.text import CountVectorizer

from gensim.models import Word2Vec, KeyedVectors

Data: 20newsgroups
We get the document-term matrix

In [5]:
# categories = ['talk.politics.guns', 'sci.space', 'soc.religion.christian',
#               'misc.forsale', 'rec.sport.baseball', 'comp.sys.mac.hardware']
categories = ['talk.politics.guns', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories)
vectorizer = CountVectorizer(stop_words = 'english', min_df=.01, max_df=0.9, 
                             token_pattern = u'(?ui)\\b[a-z]{3,}\\b')
count_vecs = vectorizer.fit_transform(newsgroups_train.data)
doc_term_matrix = count_vecs.toarray()
doc_term_matrix.shape # number of documents, number of words (in vocab)
tokenizer = vectorizer.build_tokenizer()

In [6]:
doc_term_matrix.shape[1] # vocab size

2441

In [80]:
len(vectorizer.get_feature_names())

2441

In [0]:
dict_word_freq = dict(zip(vectorizer.get_feature_names(), list(doc_term_matrix.sum(0))))

ragged array of words in each document (by index in vocabulary)

In [0]:
# def countsToInput(row):
#   return np.repeat(np.arange(doc_term_matrix.shape[1]),row)
  
# def numWords(row):
#   return row.sum()

# N_train = np.apply_along_axis(numWords, axis=1, arr=doc_term_matrix)
# data_train = []
# for d in range(doc_term_matrix.shape[0]):
#   data_train.append(torch.from_numpy(countsToInput(doc_term_matrix[d])))

In [0]:
from google.colab import drive


## Word2vec

In [8]:
# ideally, we would do some preprocessing
newsgroups_train_preproc = []
for document in newsgroups_train.data:
    newsgroups_train_preproc.append(document.split())

# make the model
w2v = Word2Vec(sg=1, negative=5, size=100, window=10, min_count=1, max_vocab_size=None, max_final_vocab=None)
# w2v.build_vocab(newsgroups_train_preproc)
w2v.build_vocab_from_freq(word_freq = dict_word_freq)
# train the model
w2v.train(sentences=newsgroups_train_preproc,epochs=10, total_examples=doc_term_matrix.shape[1])
# save the model
# w2v.save("sg_1_M2")

(625063, 3791210)

In [9]:
len(set([item for sublist in newsgroups_train_preproc for item in sublist]))

51319

In [10]:
torch.tensor(w2v.syn1neg).shape

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn1neg` (Attribute will be removed in 4.0.0, use self.trainables.syn1neg instead).
  """Entry point for launching an IPython kernel.


torch.Size([2441, 100])

In [11]:
len(w2v.wv.vocab)

2441

In [12]:
doc_term_matrix.shape[1] == len(w2v.wv.vocab)

True

In [13]:
w2v.syn1neg

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn1neg` (Attribute will be removed in 4.0.0, use self.trainables.syn1neg instead).
  """Entry point for launching an IPython kernel.


array([[-0.26420075,  0.00585905,  0.22831912, ...,  0.64760387,
         0.18856551,  0.65869856],
       [-0.23667611,  0.00330805,  0.20415191, ...,  0.57213134,
         0.16721836,  0.58668435],
       [ 0.07048804,  0.048697  ,  0.09646006, ...,  0.23505957,
        -0.1924888 ,  0.49675873],
       ...,
       [-0.12941656,  0.08567844, -0.01250011, ...,  0.07879993,
         0.07050155,  0.20635433],
       [ 0.02957424, -0.04086953,  0.00365244, ...,  0.15197736,
         0.03688794,  0.1449362 ],
       [-0.1434233 , -0.00083163,  0.13793549, ...,  0.35631266,
         0.10791391,  0.36240584]], dtype=float32)

In [14]:
w2v.wv.most_similar("university")

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('students', 0.9315541982650757),
 ('standard', 0.9139469861984253),
 ('education', 0.9031931161880493),
 ('college', 0.8969163298606873),
 ('electronic', 0.8959286212921143),
 ('books', 0.888676643371582),
 ('greatly', 0.8844950199127197),
 ('papers', 0.8828896284103394),
 ('americans', 0.8791347742080688),
 ('mac', 0.8752748966217041)]

## Setup for Model

In [0]:
# from types import SimpleNamespace
# args_dict = {"batch_size" : 50, "epochs" : 50, "no_cuda" : False, "seed" : 1, "log_interval" : 10}
# args = SimpleNamespace(**args_dict)
# args.epochs
# args.cuda = not args.no_cuda and torch.cuda.is_available()

args_dict = {"batch_size" : 50, "epochs" : 30, "no_cuda" : False, "seed" : 1, "log_interval" : 100}
args = SimpleNamespace(**args_dict)
args.cuda = not args.no_cuda and torch.cuda.is_available()

torch.manual_seed(args.seed)

device = torch.device("cuda" if args.cuda else "cpu")

kwargs = {'num_workers': 1, 'pin_memory': True} if args.cuda else {}
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.ToTensor()),
    batch_size=args.batch_size, shuffle=True, **kwargs)
test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, transform=transforms.ToTensor()),
    batch_size=args.batch_size, shuffle=True, **kwargs)





Define model

In [0]:
class VAE(nn.Module):
    def __init__(self, vocab_size, num_docs, wordvec_dim, encoder_hidden, rt_normal_dim, K):
        super(VAE, self).__init__()
        
        vocab_size = vocab_size
        wordvec_dim = wordvec_dim
        encoder_hidden = encoder_hidden
        rp_normal_dim = rt_normal_dim
        K = K
        self.num_docs = num_docs
        
        self.word_embedding = nn.Embedding(vocab_size, wordvec_dim) # decoder
#         self.word_embedding = nn.Embedding.from_pretrained(torch.tensor(w2v.syn1neg), freeze=True)
        self.topic_embedding = nn.Embedding(K, wordvec_dim) # decoder
        self.lin1 = nn.Linear(vocab_size, encoder_hidden) # encoder
        self.mean = nn.Linear(encoder_hidden, rp_normal_dim) # encoder
        self.logvar = nn.Linear(encoder_hidden, rp_normal_dim) # encoder
        self.lin2 = nn.Linear(rp_normal_dim, K) # decoder 
        #self.topicslayer = nn.Linear(wordvec_dim, K) # decoder
        
        self.beta = torch.zeros([K, vocab_size], dtype = torch.float32) # decoder
        #self.theta = torch.zeros([10, K], dtype = torch.float32)

    def encode(self, x):
        h1 = F.relu(self.lin1(x))
        return self.mean(h1), self.logvar(h1)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5*logvar) # get sigma
        eps = torch.randn_like(std) # get epsilon, generated from N(0, I_k) where k is dimension of std: k x 1
        return eps.mul(std).add_(mu) # this gives x ~ N(mu, var)
        # note: .mul is element-wise multiplication - this is fine, since sigma is diagonal matrix

      
    def decode(self, z):
        x = self.lin2(z) 
        theta = F.softmax(x, dim = 1) # to get theta, dim = batch size x K
        #word_dot_topic = self.topicslayer(self.word_embedding.weight) # weights corresp to topic vector
        self.beta = F.softmax(torch.mm(self.word_embedding.weight, 
                                       torch.transpose(self.topic_embedding.weight, 0, 1)), dim = 0) # beta, dim = V x K
        log_theta_dot_beta = torch.log(torch.mm(theta, torch.transpose(self.beta, 0, 1))) # dim = batch size x V
        #theta_dot_beta = torch.exp(log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0))
        ####log_theta_dot_beta_normalized = log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0)
        return log_theta_dot_beta ####log_theta_dot_beta_normalized
        
    def forward(self, doc):
        mu, logvar = self.encode(doc)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar, self.topic_embedding.weight

Load training data (separate into batches)

In [0]:
# mnist_train_loader = torch.utils.data.DataLoader(
#     datasets.MNIST('../data', train=True, download=True,
#                    transform=transforms.ToTensor()),
#     batch_size=args.batch_size, shuffle=True, **kwargs)
# # enumerate(train_loader)

train_data = torch.utils.data.TensorDataset(torch.tensor(doc_term_matrix))
train_loader = torch.utils.data.DataLoader(train_data,                                            
    batch_size = args.batch_size, shuffle = True)

instantiate model and define functions for training

In [0]:
model = VAE(vocab_size = doc_term_matrix.shape[1], 
            num_docs = doc_term_matrix.shape[0], 
            wordvec_dim = 100, 
            encoder_hidden = 256, 
            rt_normal_dim = 75, 
            K = 2).to(device) 
      
optimizer = optim.Adam(model.parameters(), lr=1e-3)
# optimizer = optim.RMSprop(model.parameters(), lr = 1e-3)

# Reconstruction + KL divergence losses summed over all elements and batch
def loss_function(data, train_loader, log_theta_dot_beta, x, mu, logvar, t):
    vocab_size = doc_term_matrix.shape[1]
    rt_normal_dim = 75
    # multiply by vocab_size / len(train_loader.dataset) -- this didn't work for any of the 3 possible locations      https://vxlabs.com/2017/12/08/variational-autoencoder-in-pytorch-commented-and-annotated/
    #  1.0 / (len(train_loader.dataset) * vocab_size) -- also didn't work
    
#     BCE = data[0].shape[0] * 1.0 / len(train_loader.dataset) * log_theta_dot_beta.sum() # MC est for expected log lik 

    KLD = (-0.5) * torch.sum(1 + logvar - mu.pow(2) - logvar.exp()) # KL divergence; it's fine to sum them all up now, rather than for each sample in mini-batch, because they'll all be summed up anyways
    
    BCE = log_theta_dot_beta.sum()
#     KLD = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())

#     K = t.shape[0]
#     arccos = []
#     for j in range(K):
#         for k in range(j, K):
#             arccos.append(torch.acos(torch.dot(t[:, j], t[:, k]) /
#                                                    (max(t[:, j].norm() * t[:, k].norm(), 1e-5))))
#             arccos.append(F.cosine_similarity(t[:, j], t[:, k]))
#     arccos = torch.tensor(arccos)
#     print(arccos.max())
#     zeta = (1 / (K * K)) * arccos.sum()
#     nu = torch.zeros(1)
#     print("zeta: " + str(zeta) + "nu: " + str(nu))
#     for a in arccos:
#         nu = nu.add((a - zeta).pow(2))
#     nu = (1 / (K * K)) * nu

    print("BCE: " + "{:.2f}".format(float(BCE)))
    print("KLD: " + "{:.2f}".format(float(KLD)))
    print("Loss: " + "{:.2f}".format(float(- BCE + KLD)))
    
    return data[0].shape[0] * 1.0 / len(train_loader.dataset) * (-BCE + KLD)

  
  


enc_variables = list(model.lin1.parameters()) + list(model.mean.parameters()) + list(model.logvar.parameters())
dec_variables = list(model.word_embedding.parameters()) + list(model.lin2.parameters()) + list(model.topic_embedding.parameters())

optim_enc = optim.Adam(enc_variables, lr=1e-3)
optim_dec = optim.Adam(dec_variables, lr=1e-3)

def train(epoch):
    model.train()
    train_loss = 0
    for switch in range(2):
        if switch == 0:
            print("updating encoder variables")
            optimizer = optim_enc
        else:
            print("updating decoder variables")
            optimizer = optim_dec
    for batch_idx, data in enumerate(train_loader):
#         data = data.to(device)
        optimizer.zero_grad()
        log_theta_beta, mu, logvar, topic_vecs = model(data[0].float())
        loss = loss_function(data, train_loader, log_theta_beta, data, mu, logvar, topic_vecs)
        loss.backward()
        train_loss += loss.item()
        optimizer.step()
        if batch_idx % args.log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * data[0].shape[0], len(train_loader.dataset),
                100. * batch_idx / len(train_loader),
#                 loss.item() / data[0].shape[0]))
                loss.item() ))

    print('====> Epoch: {} Average loss: {:.4f}'.format(
          epoch, train_loss / len(train_loader.dataset)))

    return train_loss / len(train_loader.dataset)


# def test(epoch):
#     model.eval()
#     test_loss = 0
#     with torch.no_grad():
#         for i, (data, _) in enumerate(test_loader):
#             data = data.to(device)
#             recon_batch, mu, logvar = model(data)
#             test_loss += loss_function(recon_batch, data, mu, logvar).item()
#             if i == 0:
#                 n = min(data.size(0), 8)
#                 comparison = torch.cat([data[:n],
#                                       recon_batch.view(args.batch_size, 1, 28, 28)[:n]])
# #                 save_image(comparison.cpu(),
# #                          'results/reconstruction_' + str(epoch) + '.png', nrow=n)

#     test_loss /= len(test_loader.dataset)
#     print('====> Test set loss: {:.4f}'.format(test_loss))

# if __name__ == "__main__":
#     for epoch in range(1, args.epochs + 1):
#         train(epoch)
#         test(epoch)
#         with torch.no_grad():
#             sample = torch.randn(64, 20).to(device)
#             sample = model.decode(sample).cpu()
#             save_image(sample.view(64, 1, 28, 28),
#                        'results/sample_' + str(epoch) + '.png')

 train the model

In [34]:
losses = []
for epoch in range(1, args.epochs + 1):
    losses.append(train(epoch))
#     if epoch > 1:
#         if np.abs(losses[epoch-1] - losses[epoch-2]) < 1e-2:
#             break



# why is KL going to 0 (and has negative sign sometimes, even though it's 0)? - this occurs when switch is off.
# when switch is on, KL is small, but never 0.
# smaller dimension for normal parameters leads to smaller KL



updating encoder variables
updating decoder variables
BCE: -3200579.00
KLD: 31.99
Loss: 3200611.00
Train Epoch: 1 [0/1139 (0%)]	Loss: 140500.921875
BCE: -3175138.75
KLD: 39.72
Loss: 3175178.50
BCE: -3153130.00
KLD: 20.02
Loss: 3153150.00
BCE: -3129754.00
KLD: 34.77
Loss: 3129788.75
BCE: -3101332.75
KLD: 269.40
Loss: 3101602.25
BCE: -3083434.25
KLD: 24.72
Loss: 3083459.00
BCE: -3060193.50
KLD: 17.08
Loss: 3060210.50
BCE: -3032922.75
KLD: 40.22
Loss: 3032963.00
BCE: -3011908.00
KLD: 22.91
Loss: 3011931.00
BCE: -2988769.00
KLD: 23.15
Loss: 2988792.25
BCE: -2966027.00
KLD: 20.82
Loss: 2966047.75
BCE: -2940860.50
KLD: 40.97
Loss: 2940901.50
BCE: -2916207.50
KLD: 40.74
Loss: 2916248.25
BCE: -2898493.00
KLD: 24.53
Loss: 2898517.50
BCE: -2874221.00
KLD: 18.73
Loss: 2874239.75
BCE: -2849180.25
KLD: 34.82
Loss: 2849215.00
BCE: -2824984.50
KLD: 24.56
Loss: 2825009.00
BCE: -2803999.25
KLD: 15.41
Loss: 2804014.75
BCE: -2782209.75
KLD: 21.98
Loss: 2782231.75
BCE: -2762459.50
KLD: 32.09
Loss: 2762491

In [35]:
model.beta
_, ind = torch.sort(model.beta, 0)
# ind.numpy()[0:50, 0] - ind.numpy()[0:50, 1]
print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:25, 0])
print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:25, 1])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 2])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 3])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 4])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 5])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 7])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 8])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 9])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 15])
# print(np.array(vectorizer.get_feature_names())[ind.numpy()][0:20, 19])

['present' 'background' 'ability' 'bms' 'car' 'letters' 'hardware'
 'version' 'try' 'handheld' 'manufacture' 'governments' 'sure' 'offered'
 'planning' 'scott' 'security' 'function' 'escaped' 'bob' 'apparently'
 'reading' 'editor' 'inside' 'lets']
['minutes' 'utzoo' 'earlier' 'view' 'tactics' 'relatively' 'body'
 'pressure' 'site' 'helps' 'student' 'relative' 'conducted' 'twist'
 'mission' 'account' 'nation' 'earth' 'consideration' 'desk' 'urbana'
 'sex' 'wouldn' 'need' 'mention']


##  Stuff

In [43]:
model.beta

tensor([[1.0554e-03, 3.9097e-13],
        [6.3868e-16, 6.6957e-04],
        [1.9011e-26, 6.6957e-04],
        ...,
        [1.0554e-03, 1.0889e-09],
        [4.1879e-09, 6.6956e-04],
        [1.0554e-03, 1.9359e-16]], grad_fn=<SoftmaxBackward>)

In [19]:
# a = torch.randn(100, 128)
a = torch.tensor([[1,2,3], [4,5,6]]).float()
b = torch.tensor([[1,2,3], [4,5,6]]).float()

F.cosine_similarity(a, b)

tensor([1.0000, 1.0000])

Get topic distributions

In [0]:
# unscaled_topics = torch.mm(model.word_embedding(torch.tensor(np.arange(doc_term_matrix.shape[1]))),
#          torch.transpose(model.topicslayer.weight, 0, 1))
# topic_dist = torch.softmax(unscaled_topics, dim = 0)
# topic_dist.sum(dim = 0)

This one helped us a lot

In [0]:
#model.encode(torch.LongTensor(doc_term_matrix[0]))
#input = torch.tensor(doc_term_matrix).float()
input = torch.tensor(doc_term_matrix).float()[[0, 1], ]
mu, sigma = model.encode(input)
z = model.reparameterize(mu, sigma)
# model.decode(x, input.shape[0])

x = model.fc3(z)
theta = F.softmax(x) # to get theta
embedding_matrix = model.word_embedding(torch.tensor(np.arange(14)))
word_dot_topic = model.fc4(embedding_matrix) # weights corresp to topic vector
beta = F.softmax(word_dot_topic)
log_theta_dot_beta = torch.log(torch.mm(theta, torch.transpose(beta, 0, 1)))
#theta_dot_beta = torch.exp(log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0))
log_theta_dot_beta_normalized = log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0)
# print(theta.shape)
# print(theta)
# print(embedding_matrix)
# print(word_dot_topic)
print(beta.shape)
print(beta)
print(log_theta_dot_beta)
print(torch.exp(log_theta_dot_beta_normalized))


In [0]:
#model.encode(torch.LongTensor(doc_term_matrix[0]))
#input = torch.tensor(doc_term_matrix).float()
input = torch.tensor(doc_term_matrix).float()[[0, 1], ]
print(input)
mu, sigma = model.encode(input)
z = model.reparameterize(mu, sigma)
print(z)
# model.decode(x, input.shape[0])


# x = model.lin2(z)
# theta = F.softmax(x) # to get theta
# embedding_matrix = model.word_embedding(torch.tensor(np.arange(model.num_docs)))
# word_dot_topic = model.topicslayer(embedding_matrix) # weights corresp to topic vector
# model.beta = F.softmax(word_dot_topic, dim = 0)
# log_theta_dot_beta = torch.log(torch.mm(theta, torch.transpose(model.beta, 0, 1)))
# #theta_dot_beta = torch.exp(log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0))
# log_theta_dot_beta_normalized = log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0)
# print(embedding_matrix.shape) # dim of embedding matrix is 1544 x 100


x = model.lin2(z)
theta = F.softmax(x, 1) # to get theta
print(theta.sum(1))
embedding_matrix = model.word_embedding.weight
print(model.word_embedding(torch.tensor(np.arange(model.num_docs))).shape)
print(embedding_matrix.shape)
word_dot_topic = model.topicslayer(embedding_matrix) # weights corresp to topic vector
model.beta = F.softmax(word_dot_topic, dim = 0)
log_theta_dot_beta = torch.log(torch.mm(theta, torch.transpose(model.beta, 0, 1)))
#theta_dot_beta = torch.exp(log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0))
log_theta_dot_beta_normalized = log_theta_dot_beta - torch.logsumexp(log_theta_dot_beta, dim = 0)
# print(embedding_matrix.shape) # dim of embedding matrix is still 1544 x 100


In [50]:
###########################
###########################
###########################

test_input = torch.tensor(doc_term_matrix).float()[[0, 1], ] # pretend_batch_size = 2
# print(test_input.shape) # 2 x 2441, where 2441 is vocab size
mu, logvar = model.encode(test_input)
# print(mu.shape) # 2 x 50
# print(sigma.shape) # 2 x 50
z = model.reparameterize(mu, sigma) # 2 x 50
# print(z.shape) # 2 x 50
output = model.decode(z)
# print(output)
# print(output.shape)

pretend_num_docs = 50
pretend_batch_size = test_input.shape[0]
#print(output.sum())
BCE = pretend_num_docs * 1.0 / pretend_batch_size * output.sum() # we sum the log probabilities
# print(1 + logvar - mu.pow(2) - logvar.exp())
KLD0 = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
print(logvar)
#KLD1 = -0.5 * torch.sum(2 + torch.sum(torch.cumprod(logvar)) - torch.mm(torch.transpose(mu, 1, 0),mu) - logvar.exp()) # this is a number, should be 
############################################################################################################
#KLD2 = 0.5 * (torch.sum(logvar.exp()) + torch.dot(mu, mu) - 50 - torch.log(torch.cumprod(logvar))) ###########################
# print(float(BCE))

# print("BCE: " + "{:.2f}".format(float(BCE)))
# print("KLD: " + "{:.2f}".format(float(KLD)))
# print("Loss: " + "{:.2f}".format(float(- BCE + KLD)))
# return - BCE + KLD # - .1 * (zeta - nu)

tensor([[-0.0176,  0.0258,  0.2086, -0.0757, -0.1349,  0.1515,  0.0422,  0.1266,
          0.1552,  0.0714, -0.1026,  0.0122, -0.0432, -0.0601, -0.0545, -0.0498,
          0.0034, -0.1475, -0.1544, -0.0403, -0.0020,  0.0638, -0.1058,  0.0358,
         -0.1366, -0.1131,  0.0661, -0.0645,  0.0669,  0.0143,  0.0352,  0.1203,
         -0.0325, -0.0359,  0.1152,  0.0315, -0.1065,  0.0167,  0.0462, -0.0026,
         -0.0827,  0.0001, -0.0119,  0.0560,  0.1036, -0.0483, -0.0862,  0.0005,
          0.0187,  0.0275],
        [-0.0438,  0.0082,  0.0904, -0.0102, -0.0217, -0.0268,  0.0012, -0.0640,
          0.0917,  0.0690, -0.0300, -0.0058,  0.0595, -0.0108, -0.0603, -0.0158,
          0.0698, -0.0569, -0.0790,  0.0202,  0.0228,  0.0589, -0.0955,  0.0672,
         -0.0046, -0.0454, -0.0373, -0.0053,  0.0295, -0.0219, -0.0386, -0.0106,
         -0.0526,  0.0714,  0.0268,  0.0146,  0.0012, -0.0256,  0.0176,  0.0066,
         -0.0199,  0.1099,  0.0021,  0.0288,  0.0588,  0.0684, -0.0177,  0.0291,


In [83]:
# X'X
torch.mm(torch.transpose(torch.tensor([[1, 2], [3, 4]]), 1, 0),torch.tensor([[1, 2], [3, 4]]))

tensor([[10, 14],
        [14, 20]])

# Topic Coherence

In [0]:
from itertools import product

def topic_coherence(beta, M, doc_term_matrix):
  K = beta.shape[1] # beta has dim V x K
  coherences = np.zeros(K)
  for t in range(K):
    index = np.argsort(-beta[:, t])[0:M]
    cart_prod = product(list(index), list(index))
    for ind1, ind2 in cart_prod:
      if ind1 == ind2:
        pass
      else:
        d_ind1 = (doc_term_matrix[:, ind1] > 0).sum()
        d_ind12 = ((doc_term_matrix[:, ind1] > 0) & (doc_term_matrix[:, ind2] > 0)).sum()
        coherences[t] += np.log1p(d_ind12) - np.log(d_ind1)

  return coherences

In [37]:
topic_coherence(model.beta.detach().numpy(), 20, doc_term_matrix)

array([-1002.65439037,  -970.85404501])